package com.byron.entity;

import java.util.Date;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.id
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_name
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.create_time
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.modify_time
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.id
     *
     * @return the value of dept.id
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.id
     *
     * @param id the value for dept.id
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_name
     *
     * @return the value of dept.dept_name
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_name
     *
     * @param deptName the value for dept.dept_name
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.create_time
     *
     * @return the value of dept.create_time
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.create_time
     *
     * @param createTime the value for dept.create_time
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.modify_time
     *
     * @return the value of dept.modify_time
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.modify_time
     *
     * @param modifyTime the value for dept.modify_time
     *
     * @mbggenerated Thu Aug 10 16:01:18 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}